base_count_desc: ''
base_count_multiplier: 1
base_count_prefix: ''
custom_logo: /opt/images/logo_ntnu.png
custom_logo_title: Genomics Core Facility
custom_logo_url: https://www.ntnu.edu/mh/gcf
extra_fn_clean_exts:
- .gz
- .fastq
- _screen.txt
- .namesorted
- _fastp
- .fastp
fastqscreen_simpleplot: true
intro_text: This report is generated for projects run at Genomics Core Facility, NTNU,
  Trondheim. The results are reported per sample.
megaqc_access_token: wEW80XSMp0zmWBGYoH29iwPb3izPeYpUvEE0QrCFE3Q1q8b9zP5FusbuFqFFi9dUrnyQGZEJhsRBQr16
megaqc_url: http://gcf-megaqc.medisin.ntnu.no:443/api/upload_data
read_count_desc: ''
read_count_multiplier: 1
read_count_prefix: ''
remove_sections:
- fastqc_rnaseq_sequence_counts
- fastqc_rnaseq_per_base_sequence_quality
- fastqc_rnaseq_per_sequence_quality_scores
- fastqc_rnaseq_per_sequence_gc_content
- fastqc_rnaseq_per_base_n_content
- fastqc_rnaseq_sequence_duplication_levels
- fastqc_rnaseq_status_checks
- fastqc_sequence_counts
- fastqc_per_base_sequence_quality
- fastqc_per_sequence_quality_scores
- fastqc_per_sequence_gc_content
- fastqc_per_base_n_content
- fastqc_sequence_duplication_levels
- fastqc_status_checks
report_header_info:
- Contact E-mail: arnar.flatberg@ntnu.no
- Sequencing Platform: NextSeq 500
- Read Geometry: 'Paired end - forward read length (R1): 28, reverse read length (R2):
    56'
- Organism: mus_musculus
- Lib prep kit: 10X Genomics Chromium Single Cell 3p GEM Library & Gel Bead Kit v3
report_section_order:
  cellranger:
    order: 1000
  fastp:
    order: 950
  fastq_screen:
    order: 800
  fastqc:
    order: 900
  fastqc_rnaseq:
    order: 900
  regions:
    order: 1000
table_columns_placement:
  fastp:
    after_filtering_gc_content: 116
    before_filtering_total_reads: 110
    pct_adapter: 114
    pct_surviving: 112
table_columns_visible:
  fastp:
    pct_duplication: false
thousandsSep_format: ' '
title: GCF-2020-739
